version: '2'
services:
  rss-indexer:
    image: node:12.20.0-alpine3.10
    restart: always
    ports:
      - 8090:8090
    volumes:
      - ./:/indexer
    command: bash -c "cd /indexer && npm start"
